name: Terraform CI

on:
  push:
    branches:
      - develop
      - main

jobs:
  terraform_ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '0.13'  # Use the desired version (e.g., 0.13, 0.14, 1.0, etc.)

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate