name: Terraform CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  terraform_ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Composite Action
      uses: ./.github/actions/terraform-ci
      with:
        tf-file-path: './terraform/main.tf'