name: Terraform CI

on:
  push:
    branches:
      - develop
      - main

jobs:
  terraform_ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Fmt Check
      run: |
        TERRAFORM_FILES=$(git ls-files '*.tf')
        if [ -n "$TERRAFORM_FILES" ]; then
          terraform fmt -check -recursive $TERRAFORM_FILES
        else
          echo "No Terraform files (*.tf) found."
        fi
